version: '3.9'
services:
  letterweb-app:
    build: .
    container_name: letterweb-app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: letterweb-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - letterweb-app
    restart: unless-stopped
